"""
    Dataset Cleaning Library
"""

import spacy
import re
from nltk.stem.snowball import SnowballStemmer

# chargement du modèle grammaticale
nlp = spacy.load("fr_core_news_sm") 
lexique = loadlex("LexHaine.txt")
stop = loadstop("stopW.txt")
stemmer = SnowballStemmer(language='french')

def DataClean(data, lexique, nlp):
    """ Corrects and normalizes a dataset.
    
    Args:
        data (file): Input file (1 tweet per line).
        lexique (file): Lexicon for correcting hate speech expressions.
        nlp (spacy model): Grammatical model for tokenization.
    """
    outmin = str(data.split(".")[0]) + "Min.txt"
    min = open(outmin, 'a')
    with open(data, 'r') as data:
        for line in data:
            lineClean = ""
            words = decoupeMots(line, nlp)
            for word in words:
                word = rplace(rexochar(rhttp(rligature(word))).lower(), lexique)
                if len(lineClean) == 0 or word in ".,!?:;.":
                    lineClean = lineClean + str(word)
                elif lineClean[-1] in "'-’#":
                    lineClean = lineClean + str(word)
                elif word[0] in "-":
                    lineClean = lineClean + str(word)
                else:
                    lineClean = lineClean + " " + str(word)
            min.write(lineClean + "\n")
    min.close()

def DataStd(data, nlp, stop):
    """Filters data using a stop words list and applies stemming to the results.

    Args:
        data (file): Data file (1 tweet per line).
        nlp (spacy model): Language-specific spaCy object.
        stop (list): List of stop words.
    """
    outstd = outmin = str(data.split(".")[0][:-3]) + "Std.txt"
    std = open(outstd, 'a')
    with open(data, 'r') as data:
        for line in data:
            lineStd = ""
            words = decoupeMots(line, nlp)
            for word in words:
                if word in stop:
                    pass
                else:
                    word = stemmer.stem(word)
                    if len(lineStd)==0 or word in ".,!?:;." or  word[0] in "-" or lineStd[-1] in "'-’#":
                        lineStd = lineStd + word
                    else:
                        lineStd = lineStd + " " + word
            std.write(lineStd)
    std.close()

def DataLem(data, nlp, stop):
    """Filters data using a stop words list and applies lemmatization to the results.

    Args:
        data (file): Data file (1 tweet per line).
        nlp (spacy model): Language-specific spaCy object.
        stop (list): List of stop words.
    """
    outlem = outmin = str(data.split(".")[0][:-3]) + "lem.txt"
    lem = open(outlem, 'a')
    with open(data, 'r') as data:
        for line in data:
            # retrait des stop words:
            lineStop = ""
            words = decoupeMots(line, nlp)
            for word in words:
                if word in stop:
                    pass
                else:
                    if len(lineStop)==0 or word in ".,!?:;." or  word[0] in "-" or lineStop[-1] in "'-’#":
                        lineStop = lineStop+ word
                    else:
                        lineStop = lineStop + " " + word
            # lemmatisation:
            listLem = [X.lemma_ for X in nlp(lineStop)]
            lineLem = ""
            for word in listLem:
                if len(lineLem)==0 or word in ".,!?:;." or  word[0] in "-" or lineLem[-1] in "'-’#":
                    lineLem = lineLem + word
                else:
                    lineLem = lineLem + " " + word
            lem.write(lineLem)
    lem.close()

def noemptyframe(original, min, std):
    """Processes files generated by previous functions to remove empty lines from the 
    cleaned (*min) version, ensuring line-to-line correspondence is maintained.

    Args:
        original (file): Original raw data file.
        min (file): Cleaned data file.
        std (file): Standardized data file.
    """
    Or = loadline(original) 
    Std = loadline(std)
    indexMin = 0
    outOr = open(str(original.split('.')[0]) + "_NEF.txt", 'a')
    outStd = open(str(std.split('.')[0]) + "_NEF.txt", 'a')    
    outMin = open(str(min.split('.')[0]) + "_NEF.txt", 'a')
    with open(min, 'r') as data:
        for line in data:
            if line != "\n":
                outOr.write(Or[indexMin])
                outStd.write(Std[indexMin])
                outMin.write(line)
            indexMin += 1
    outOr.close()
    outStd.close()
    outMin.close()

def loadlex(lex):
    """Loads a lexicon (list of lists).

    Args:
        lex (file): File containing word lists separated by ','.

    Returns:
        list: A list of lists containing the words.
    """
    with open(lex, 'r') as data:
        lexique = []
        for line in data:
            lineR = []
            temp = line.split(", ")
            for e in temp:
                lineR.append(e.split("\n")[0])
            lexique.append(lineR)
        return lexique

def loadstop(stop):
    """Loads a word list (stopwords).

    Args:
        stop (file): File containing one word per line.

    Returns:
        list: A list of words.
    """
    with open(stop, 'r') as data:
        stop = []
        for line in data:
            stop.append(line.split('\n')[0])
        return stop

def loadline(file):
    """Loads all lines from a file into a list.

    Args:
        file (file): Data file.

    Returns:
        list: A list of all lines.
    """
    with open(file, 'r') as data:
        temp = []
        for line in data:
            temp.append(line)
        return temp

def decoupeMots(s, nlp):
    """Tokenizes a string into a list of words.
    
    Args:
        s (string): Input line.
        nlp (spacy model): spaCy NLP object.
    """
    temp = nlp(s)
    return [X.text for X in temp]

def rligature(w):
    """
    Normalizes ligatures into distinct letters.
    
    :param w: Input string.
    :return: String without œ and/or æ.
    """
    if "œ" in w:
        w = w.replace("œ","oe")
    if "Œ" in w:
        w = w.replace("Œ","oe")
    if "æ" in w:
        w = w.replace("æ", "ae")
    if "Æ" in w:
        w = w.replace("Æ", "ae")
    return w

def rhttp(w):
    """
    Normalizes or removes URLs.
    
    :param w: Input string.
    :return: String without the URL.
    """
    if w.startswith("http"):
        w = ''
    return w

def rexochar(w):
    """
    Normalizes text by removing 'exotic' or non-standard characters 
    relative to the French language.
    
    :param w: Input string.
    :return: String without special characters.
    """
    temp = re.sub('[^a-zA-Z0-9àÀâÂäÄéÉèÈëËêÊïÏîÎôÔöÖùÙûÛüÜÿçÇ ;:.,?!+-/*=\'`()€#’&]+', '', w)
    if (temp != w):
        w = temp
    return w

def rplace(w, liste):
    """Checks if a word is present in a specific list; if so, replaces it 
    with the first element (canonical form) of that list.

    Args:
        w (string): Input word.
        liste (list of lists): Lexicon of word variations.

    Returns:
        string: The modified or original word.
    """
    for e in liste:
        if w in e:
            w = e[0] 
    return w

def countL(data):
    """Counts the number of lines in a file.
    
    Args:
        data (file): Input file.

    Returns:
        int: Total number of lines.
    """
    result = 0
    with open(data, 'r') as file:
        for line in file:
            result +=1
        return result
